export const categories = [
  {
    name: 'Regular Bills',
    id: 0,
    state: false,
    amount: 0,
    iconName: 'ios-calculator',
    expense: 0,
    children: [
      {
        name: 'Rent',
        id: 0,
        state: false,
        amount: 0,
        iconName: 'ios-airplane',
      },
      {
        name: 'Home loan repayment',
        id: 1,
        state: false,
        amount: 0,
        iconName: 'ios-airplane',
      },
      {
        name: 'Gas',
        id: 2,
        state: false,
        amount: 0,
        iconName: 'ios-airplane',
      },
      {
        name: 'Electricity',
        id: 3,
        state: false,
        amount: 0,
        iconName: 'ios-airplane',
      },
      {
        name: 'Water',
        id: 4,
        state: false,
        amount: 0,
        iconName: 'ios-airplane',
      },
      {
        name: 'Council rates',
        id: 5,
        state: false,
        amount: 0,
        iconName: 'ios-airplane',
      },
      {
        name: 'Home content insurance',
        id: 6,
        state: false,
        amount: 0,
        iconName: 'ios-airplane',
      },
    ],
  },
  {
    name: 'Pay as you go',
    id: 1,
    children: [{}],
    state: false,
    amount: 0,
    expense: 0,
    iconName: 'ios-card',
    children: [
      {
        name: 'Drink',
        id: 0,
        state: false,
        amount: 0,
        iconName: 'ios-airplane',
      },
      {
        name: 'Coffee',
        id: 1,
        state: false,
        amount: 0,
        iconName: 'ios-airplane',
      },
      {
        name: 'Date',
        id: 2,
        state: false,
        amount: 0,
        iconName: 'ios-airplane',
      },
      {
        name: 'Climb mountain',
        id: 3,
        state: false,
        amount: 0,
        iconName: 'ios-airplane',
      },
      {
        name: 'Go to beach',
        id: 4,
        state: false,
        amount: 0,
        iconName: 'ios-airplane',
      },
      {
        name: 'Catch a movie',
        id: 5,
        state: false,
        amount: 0,
        iconName: 'ios-airplane',
      },
      {
        name: 'Đà Lạt',
        id: 6,
        state: false,
        amount: 0,
        iconName: 'ios-airplane',
      },
    ],
  },
  {
    name: 'Entertainment',
    id: 2,
    state: false,
    amount: 0,
    expense: 0,
    iconName: 'ios-airplane',
    children: [
      {
        name: 'Coffee and tea',
        id: 0,
        state: false,
        amount: 0,
        iconName: 'ios-airplane',
      },
      {
        name: 'Lunches',
        id: 1,
        state: false,
        amount: 0,
        iconName: 'ios-airplane',
      },
      {
        name: 'Take Away and Snacks',
        id: 2,
        state: false,
        amount: 0,
        iconName: 'ios-airplane',
      },
      {
        name: 'Cigarettes',
        id: 3,
        state: false,
        amount: 0,
        iconName: 'ios-airplane',
      },
      {
        name: 'Drinks and Alcohol',
        id: 4,
        state: false,
        amount: 0,
        iconName: 'ios-airplane',
      },
      {
        name: 'Bars and Clubs',
        id: 5,
        state: false,
        amount: 0,
        iconName: 'ios-airplane',
      },
      {
        name: 'Restaurants',
        id: 6,
        state: false,
        amount: 0,
        iconName: 'ios-airplane',
      },
      {
        name: 'Books',
        id: 7,
        state: false,
        amount: 0,
        iconName: 'ios-airplane',
      },
    ],
  },
];

export const categoryIncome = [
  {
    name: 'Your Take-Home Pay',
    id: 0,
    amount: 0,
    iconName: 'logo-euro',
    state: false,
  },
  {
    name: "Your Partner's Take-Home Pay",
    id: 1,
    amount: 0,
    iconName: 'ios-contacts',
    state: false,
  },
  {
    name: 'Bonuses & Overtime',
    id: 2,
    amount: 0,
    iconName: 'ios-alarm',
    state: false,
  },
  {
    name: 'Income From Savings & Investments',
    id: 3,
    amount: 0,
    iconName: 'logo-euro',
    state: false,
  },
  {
    name: 'Centrelink Benefits',
    id: 4,
    amount: 0,
    iconName: 'ios-globe',
    state: false,
  },
  {
    name: 'Family Benefit Payments',
    id: 5,
    amount: 0,
    iconName: 'md-happy',
    state: false,
  },
  {
    name: 'Child Support Received',
    id: 6,
    amount: 0,
    iconName: 'md-contacts',
    state: false,
  },
  {
    name: 'Other',
    id: 7,
    amount: 0,
    iconName: 'md-aperture',
    state: false,
  },
];
