export const categories = [
  {
    name: 'Regular Bills',
    id: 0,
    state: false,
    amount: 0,
    iconName: 'ios-calculator',
    children: [
      {
        name: 'Rent',
        id: 0,
        state: false,
        amount: 0,
        iconName: 'ios-airplane',
      },
      {
        name: 'Home loan repayment',
        id: 1,
        state: false,
        amount: 0,
        iconName: 'ios-airplane',
      },
      {
        name: 'Gas',
        id: 2,
        state: false,
        amount: 0,
        iconName: 'ios-airplane',
      },
      {
        name: 'Electricity',
        id: 3,
        state: false,
        amount: 0,
        iconName: 'ios-airplane',
      },
      {
        name: 'Water',
        id: 4,
        state: false,
        amount: 0,
        iconName: 'ios-airplane',
      },
      {
        name: 'Council rates',
        id: 5,
        state: false,
        amount: 0,
        iconName: 'ios-airplane',
      },
      {
        name: 'Home content insurance',
        id: 6,
        state: false,
        amount: 0,
        iconName: 'ios-airplane',
      },
    ],
  },
  {
    name: 'Pay as you go',
    id: 1,
    children: [{}],
    state: false,
    amount: 0,
    iconName: 'ios-card',
  },
  {
    name: 'Entertainment',
    id: 2,
    state: false,
    amount: 0,
    iconName: 'ios-airplane',
    children: [
      {
        name: 'Coffee and tea',
        id: 0,
        state: false,
        amount: 0,
        iconName: 'ios-airplane',
      },
      {
        name: 'Lunches',
        id: 1,
        state: false,
        amount: 0,
        iconName: 'ios-airplane',
      },
      {
        name: 'Take Away and Snacks',
        id: 2,
        state: false,
        amount: 0,
        iconName: 'ios-airplane',
      },
      {
        name: 'Cigarettes',
        id: 3,
        state: false,
        amount: 0,
        iconName: 'ios-airplane',
      },
      {
        name: 'Drinks and Alcohol',
        id: 4,
        state: false,
        amount: 0,
        iconName: 'ios-airplane',
      },
      {
        name: 'Bars and Clubs',
        id: 5,
        state: false,
        amount: 0,
        iconName: 'ios-airplane',
      },
      {
        name: 'Restaurants',
        id: 6,
        state: false,
        amount: 0,
        iconName: 'ios-airplane',
      },
      {
        name: 'Books',
        id: 7,
        state: false,
        amount: 0,
        iconName: 'ios-airplane',
      },
    ],
  },
];
